//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDemoQA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EcommerceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EcommerceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcommerceDemoQA.EcommerceResources", typeof(EcommerceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //textarea[@id=&apos;wpsc_checkout_form_4&apos;].
        /// </summary>
        internal static string CheckoutPage_address {
            get {
                return ResourceManager.GetString("CheckoutPage_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[contains(@name, &apos;submit_zipcode&apos;)] .
        /// </summary>
        internal static string CheckoutPage_calculatePrice {
            get {
                return ResourceManager.GetString("CheckoutPage_calculatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;wpsc_checkout_form_5&apos;].
        /// </summary>
        internal static string CheckoutPage_city {
            get {
                return ResourceManager.GetString("CheckoutPage_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@class=&apos;step2&apos;].
        /// </summary>
        internal static string CheckoutPage_continue {
            get {
                return ResourceManager.GetString("CheckoutPage_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@id=&apos;wpsc_checkout_form_7&apos;].
        /// </summary>
        internal static string CheckoutPage_country {
            get {
                return ResourceManager.GetString("CheckoutPage_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;wpsc_checkout_form_9&apos;].
        /// </summary>
        internal static string CheckoutPage_emailaddress {
            get {
                return ResourceManager.GetString("CheckoutPage_emailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@class, &apos;entry-content&apos;)].
        /// </summary>
        internal static string CheckoutPage_emptyCartContent {
            get {
                return ResourceManager.GetString("CheckoutPage_emptyCartContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;wpsc_checkout_form_2&apos;].
        /// </summary>
        internal static string CheckoutPage_firstName {
            get {
                return ResourceManager.GetString("CheckoutPage_firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;wpsc_checkout_form_3&apos;].
        /// </summary>
        internal static string CheckoutPage_lastName {
            get {
                return ResourceManager.GetString("CheckoutPage_lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[contains(@class, &apos;make_purchase wpsc_buy_button&apos;)].
        /// </summary>
        internal static string CheckoutPage_orderPurchase {
            get {
                return ResourceManager.GetString("CheckoutPage_orderPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;wpsc_checkout_form_18&apos;].
        /// </summary>
        internal static string CheckoutPage_phone {
            get {
                return ResourceManager.GetString("CheckoutPage_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@class=&apos;adjustform remove&apos;].
        /// </summary>
        internal static string CheckoutPage_remove {
            get {
                return ResourceManager.GetString("CheckoutPage_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[contains(@id, &apos;current_country&apos;)].
        /// </summary>
        internal static string CheckoutPage_selectCountry {
            get {
                return ResourceManager.GetString("CheckoutPage_selectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;pricedisplay checkout-shipping&apos;].
        /// </summary>
        internal static string CheckoutPage_shippingPriceDisplay {
            get {
                return ResourceManager.GetString("CheckoutPage_shippingPriceDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;shippingSameBilling&apos;].
        /// </summary>
        internal static string CheckoutPage_shippingSameasBilling {
            get {
                return ResourceManager.GetString("CheckoutPage_shippingSameasBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;pricedisplay checkout-total&apos;].
        /// </summary>
        internal static string CheckoutPage_totalPriceDisplay {
            get {
                return ResourceManager.GetString("CheckoutPage_totalPriceDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;user_pass&quot;].
        /// </summary>
        internal static string LoginPage_password {
            get {
                return ResourceManager.GetString("LoginPage_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;wp-submit&apos;].
        /// </summary>
        internal static string LoginPage_submit {
            get {
                return ResourceManager.GetString("LoginPage_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;user_login&quot;].
        /// </summary>
        internal static string LoginPage_UserName {
            get {
                return ResourceManager.GetString("LoginPage_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;input-button-buy&apos;].
        /// </summary>
        internal static string ProductPage_addToCart {
            get {
                return ResourceManager.GetString("ProductPage_addToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@class=&apos;continue_shopping&apos;].
        /// </summary>
        internal static string ProductPage_continueShopping {
            get {
                return ResourceManager.GetString("ProductPage_continueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@class=&apos;go_to_checkout&apos;].
        /// </summary>
        internal static string ProductPage_goToCheckout {
            get {
                return ResourceManager.GetString("ProductPage_goToCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(@class , &apos;currentprice&apos;)].
        /// </summary>
        internal static string ProductPage_productPrice {
            get {
                return ResourceManager.GetString("ProductPage_productPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;wp-admin-bar-logout&apos;].
        /// </summary>
        internal static string ProfilePage_accountLogout {
            get {
                return ResourceManager.GetString("ProfilePage_accountLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[@id=&apos;wp-admin-bar-my-account&apos;]/a[@class=&apos;ab-item&apos;].
        /// </summary>
        internal static string ProfilePage_accountSubmenu {
            get {
                return ResourceManager.GetString("ProfilePage_accountSubmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;first_name&apos;].
        /// </summary>
        internal static string ProfilePage_firstName {
            get {
                return ResourceManager.GetString("ProfilePage_firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;last_name&apos;].
        /// </summary>
        internal static string ProfilePage_lastName {
            get {
                return ResourceManager.GetString("ProfilePage_lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;submit&apos;].
        /// </summary>
        internal static string ProfilePage_updateProfile {
            get {
                return ResourceManager.GetString("ProfilePage_updateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@class,&apos;transaction-results&apos;)]/p[3].
        /// </summary>
        internal static string TransactionResultsPage_totalPrice {
            get {
                return ResourceManager.GetString("TransactionResultsPage_totalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h1[contains(@class, &apos;entry-title&apos;)].
        /// </summary>
        internal static string TransactionResultsPage_transactionHeader {
            get {
                return ResourceManager.GetString("TransactionResultsPage_transactionHeader", resourceCulture);
            }
        }
    }
}
